# Generated by Django 2.0 on 2019-01-08 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pos', models.CharField(max_length=5)),
                ('no', models.CharField(max_length=20)),
                ('slug', models.CharField(max_length=20, unique=True)),
                ('img', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('slug', models.CharField(max_length=5, unique=True)),
                ('conference', models.CharField(max_length=1)),
                ('logo', models.URLField(max_length=10)),
                ('wins', models.IntegerField()),
                ('losses', models.IntegerField()),
                ('win_percent', models.FloatField()),
                ('avg_points_for', models.FloatField()),
                ('avg_points_against', models.FloatField()),
                ('streak', models.IntegerField()),
                ('playoff_seed', models.FloatField()),
                ('division_win_percent', models.FloatField()),
                ('league_win_percentange', models.FloatField()),
                ('threepoints_or_less', models.CharField(max_length=10)),
                ('tenpoints_or_more', models.CharField(max_length=10)),
                ('vsorbetter', models.CharField(max_length=10)),
                ('vsorbelow', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nba.Team'),
        ),
    ]
