# Generated by Django 2.0.8 on 2019-01-09 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nba', '0002_auto_20190108_2316'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('away', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='away_game', to='nba.Team')),
                ('fixture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='nba.Fixture')),
                ('home', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='home_game', to='nba.Team')),
            ],
        ),
    ]
