# Generated by Django 2.0.8 on 2019-01-09 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba', '0003_fixture_game'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='away',
            new_name='away_team',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='home',
            new_name='home_team',
        ),
        migrations.AddField(
            model_name='game',
            name='away_score',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='home_score',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='date',
            field=models.DateField(unique=True),
        ),
    ]
